<a href="https://colab.research.google.com/github/NghiaH19/E-commerce/blob/main/Dataclean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tải dataset

In [ ]:
import os

os.environ['KAGGLE_API_TOKEN'] = "KGAT_6f3a8eab804f2bfea0b0dda2c03339b9"

!pip install -q -U kaggle

print("Đang tải dữ liệu, bạn chờ một chút nhé...")
!kaggle datasets download -d mkechinov/ecommerce-behavior-data-from-multi-category-store
print("Tải dữ liệu hoàn tất!")

print("Đang giải nén, bạn chờ một chút nhé...")
!unzip -q ecommerce-behavior-data-from-multi-category-store.zip -d ecommerce_data
print("Tải và giải nén hoàn tất! Tuyệt vời!")

Đang tải dữ liệu, bạn chờ một chút nhé...
Dataset URL: https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store
License(s): copyright-authors
ecommerce-behavior-data-from-multi-category-store.zip: Skipping, found more recently modified local copy (use --force to force download)
Tải dữ liệu hoàn tất!
Đang giải nén, bạn chờ một chút nhé...
replace ecommerce_data/2019-Nov.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
replace ecommerce_data/2019-Oct.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
Tải và giải nén hoàn tất! Tuyệt vời!

Xem dataset

In [ ]:
import pandas as pd

cot_can_lay = ['event_time', 'event_type', 'product_id', 'category_code', 'brand', 'price']

def xu_ly_va_co_dac(file_path):
    print(f"Đang xử lý file {file_path} (Quá trình này có thể mất 2-4 phút)...")
    df = pd.read_csv(file_path, usecols=cot_can_lay)
    df = df.dropna(subset=['category_code', 'brand'])

    df['date'] = df['event_time'].str[:10]

    df_grouped = df.groupby(['date', 'product_id', 'category_code', 'brand', 'price', 'event_type']).size().unstack(fill_value=0).reset_index()
    df_grouped = df_grouped.rename(columns={'view': 'luot_view', 'cart': 'luot_cart', 'purchase': 'luot_mua'})

    for col in ['luot_view', 'luot_cart', 'luot_mua']:
        if col not in df_grouped.columns:
            df_grouped[col] = 0

    print(f"-> Xử lý xong! File teo nhỏ xuống còn {len(df_grouped)} dòng.\n")
    del df
    return df_grouped

df_thang_10 = xu_ly_va_co_dac('ecommerce_data/2019-Oct.csv')
df_thang_11 = xu_ly_va_co_dac('ecommerce_data/2019-Nov.csv')

print("Đang gộp 2 tháng lại với nhau...")
df_final = pd.concat([df_thang_10, df_thang_11], ignore_index=True)

df_final = df_final.sort_values(by=['date', 'product_id']).reset_index(drop=True)

print("ĐÂY LÀ BỘ DỮ LIỆU CHUẨN ĐỂ ĐƯA VÀO MÔ HÌNH:")
display(df_final.head())

Đang xử lý file ecommerce_data/2019-Oct.csv (Quá trình này có thể mất 2-4 phút)...
-> Xử lý xong! File teo nhỏ xuống còn 999134 dòng.

Đang xử lý file ecommerce_data/2019-Nov.csv (Quá trình này có thể mất 2-4 phút)...
-> Xử lý xong! File teo nhỏ xuống còn 1150056 dòng.

Đang gộp 2 tháng lại với nhau...
ĐÂY LÀ BỘ DỮ LIỆU CHUẨN ĐỂ ĐƯA VÀO MÔ HÌNH:

event_type,date,product_id,category_code,brand,price,luot_cart,luot_mua,luot_view
0,2019-10-01,1001588,electronics.smartphone,meizu,128.30,0,1,17
1,2019-10-01,1001588,electronics.smartphone,meizu,128.31,0,0,47
2,2019-10-01,1002042,electronics.smartphone,samsung,89.81,0,0,7
3,2019-10-01,1002062,electronics.smartphone,samsung,77.14,0,1,13
4,2019-10-01,1002098,electronics.smartphone,samsung,370.64,0,0,62

Kết nối drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Lưu data sau xử lý

In [ ]:
import os
import pandas as pd

thu_muc_luu = '/content/drive/MyDrive/Project2_Ecommerce'
os.makedirs(thu_muc_luu, exist_ok=True)
duong_dan_file = f'{thu_muc_luu}/ecommerce_clean_data.csv'

print(f"Đang xuất file CSV và lưu lên Drive tại: {duong_dan_file} ...")
df_final.to_csv(duong_dan_file, index=False)

print("Dữ liệu đã được lưu thành công.")

Đang xuất file CSV và lưu lên Drive tại: /content/drive/MyDrive/Project2_Ecommerce/ecommerce_clean_data.csv ...
Dữ liệu đã được lưu thành công.

In [ ]:
so_dong, so_cot = df_final.shape

print(f"Bộ dữ liệu của chúng ta hiện có: {so_dong:,} dòng và {so_cot} cột.")

Bộ dữ liệu của chúng ta hiện có: 2,149,190 dòng và 8 cột.

In [ ]:
print("Đang nạp lại dữ liệu từ Google Drive...")
duong_dan_file = '/content/drive/MyDrive/Project2_Ecommerce/ecommerce_clean_data.csv'
df_final = pd.read_csv(duong_dan_file)

print(f"Nạp thành công! Bộ dữ liệu có: {df_final.shape[0]:,} dòng.")
display(df_final.head())

Đang nạp lại dữ liệu từ Google Drive...
Nạp thành công! Bộ dữ liệu có: 2,149,190 dòng.

,date,product_id,category_code,brand,price,luot_cart,luot_mua,luot_view
0,2019-10-01,1001588,electronics.smartphone,meizu,128.30,0,1,17
1,2019-10-01,1001588,electronics.smartphone,meizu,128.31,0,0,47
2,2019-10-01,1002042,electronics.smartphone,samsung,89.81,0,0,7
3,2019-10-01,1002062,electronics.smartphone,samsung,77.14,0,1,13
4,2019-10-01,1002098,electronics.smartphone,samsung,370.64,0,0,62

In [ ]:
import pandas as pd
import numpy as np

print("1. Đang gộp triệt để các dòng trùng lặp (Aggregate)...")

# Chuyển cột date về datetime chuẩn
df_final['date'] = pd.to_datetime(df_final['date'])

# Gộp các dòng trùng Product_ID và Date
# Cộng dồn lượt view/mua, lấy giá trung bình, lấy category/brand đầu tiên gặp được
df_fixed = df_final.groupby(['product_id', 'date']).agg({
    'luot_view': 'sum',
    'luot_mua': 'sum',
    'luot_cart': 'sum',
    'price': 'mean',
    'category_code': 'first',
    'brand': 'first'
}).reset_index()

print(f"   -> Sau khi gộp trùng: {len(df_fixed):,} dòng.")

# 2. Định nghĩa hàm lấp đầy ngày trống (Reindex)
def fill_missing_dates(grp):
    # Tạo dải ngày liên tục từ ngày đầu đến ngày cuối của sản phẩm đó
    all_dates = pd.date_range(start=grp['date'].min(), end=grp['date'].max(), freq='D')

    # Thiết lập index là ngày để reindex
    grp = grp.set_index('date').reindex(all_dates)

    # Những ngày mới chèn vào thì lượt view/mua/cart = 0
    grp[['luot_view', 'luot_mua', 'luot_cart']] = grp[['luot_view', 'luot_mua', 'luot_cart']].fillna(0)

    # Những thông tin cố định như Brand, Category, Price thì lấy dữ liệu gần nhất (Forward Fill)
    grp[['product_id', 'category_code', 'brand', 'price']] = grp[['product_id', 'category_code', 'brand', 'price']].ffill().bfill()

    return grp.reset_index().rename(columns={'index': 'date'})

print("2. Đang lấp đầy các ngày bị thiếu (có thể mất 1-2 phút)...")
# Áp dụng cho từng sản phẩm
df_final_perfect = df_fixed.groupby('product_id', group_keys=False).apply(fill_missing_dates)

print(f"Dữ liệu hiện có: {len(df_final_perfect):,}")

print("3. Đang tính lại Lag & Rolling trên chuỗi thời gian liên tục...")
group_prod = df_final_perfect.groupby('product_id')

df_final_perfect['day_of_week'] = df_final_perfect['date'].dt.dayofweek
df_final_perfect['is_weekend'] = df_final_perfect['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)
df_final_perfect['view_lag_1'] = group_prod['luot_view'].shift(1)
df_final_perfect['view_lag_7'] = group_prod['luot_view'].shift(7)
df_final_perfect['mua_lag_1'] = group_prod['luot_mua'].shift(1)

df_final_perfect['view_rolling_7'] = group_prod['luot_view'].transform(lambda x: x.rolling(window=7, min_periods=7).mean())

df_model_final = df_final_perfect.dropna().reset_index(drop=True)

print(f"Danh sách cột chuẩn bị lưu: {df_model_final.columns.tolist()}")
display(df_model_final.head(5))

df_model_final.to_csv('/content/drive/MyDrive/Project2_Ecommerce/ecommerce_clean_data.csv', index=False)
print("ĐÃ LƯU FILE LÊN DRIVE!")

1. Đang gộp triệt để các dòng trùng lặp (Aggregate)...
   -> Sau khi gộp trùng: 1,994,926 dòng.
2. Đang lấp đầy các ngày bị thiếu (có thể mất 1-2 phút)...

/tmp/ipykernel_27818/3286445795.py:40: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_final_perfect = df_fixed.groupby('product_id', group_keys=False).apply(fill_missing_dates)

Dữ liệu hiện có: 3,148,583
3. Đang tính lại Lag & Rolling trên chuỗi thời gian liên tục...
Danh sách cột chuẩn bị lưu: ['date', 'product_id', 'luot_view', 'luot_mua', 'luot_cart', 'price', 'category_code', 'brand', 'day_of_week', 'is_weekend', 'view_lag_1', 'view_lag_7', 'mua_lag_1', 'view_rolling_7']

,date,product_id,luot_view,luot_mua,luot_cart,price,category_code,brand,day_of_week,is_weekend,view_lag_1,view_lag_7,mua_lag_1,view_rolling_7
0,2019-10-28,1000978.0,260.0,0.0,0.0,333.490,electronics.smartphone,samsung,0,0,302.0,209.0,1.0,291.571429
1,2019-10-29,1000978.0,320.0,4.0,0.0,317.315,electronics.smartphone,samsung,1,0,260.0,308.0,0.0,293.285714
2,2019-10-30,1000978.0,235.0,1.0,0.0,301.140,electronics.smartphone,samsung,2,0,320.0,312.0,4.0,282.285714
3,2019-10-31,1000978.0,277.0,0.0,0.0,301.140,electronics.smartphone,samsung,3,0,235.0,295.0,1.0,279.714286
4,2019-11-01,1000978.0,15.0,0.0,0.0,301.140,electronics.smartphone,samsung,4,0,277.0,304.0,0.0,238.428571

ĐÃ LƯU FILE LÊN DRIVE!

In [ ]:
thu_muc_luu = '/content/drive/MyDrive/Project2_Ecommerce'
duong_dan_file = f'{thu_muc_luu}/ecommerce_clean_data.csv'

os.makedirs(thu_muc_luu, exist_ok=True)

print(f"Đang ghi đè dữ liệu mới (3 triệu dòng) vào: {duong_dan_file}...")

df_model_final.to_csv(duong_dan_file, index=False)

print("✅ ĐÃ GHI ĐÈ THÀNH CÔNG! Từ giờ bạn chỉ cần load file này là có data chuẩn nhất.")

Đang ghi đè dữ liệu mới (3 triệu dòng) vào: /content/drive/MyDrive/Project2_Ecommerce/ecommerce_clean_data.csv...
✅ ĐÃ GHI ĐÈ THÀNH CÔNG! Từ giờ bạn chỉ cần load file này là có data chuẩn nhất.